### ISSUE TITLE
asdf install v 0.1.17 does not work

### ISSUE THREAD

**Issue by shanoaice** [ndac-todoroki/asdf-v#6]
I tried to open the url showed in the output in browser and I got an 404, (url:`https://github.com/vlang/v/archive/v0.1.17.tar.gz`), only `asdf install v ref:0.1.17` works properly.

**Comment by rkyleg** [comment]
Part of the issue may be this...a quote character at the beginning of the version and a '.z' at the end in `asdf list-all`
![image](https://user-images.githubusercontent.com/4260414/62815061-c58b1300-bb04-11e9-9065-dd0697b5232c.png)

**Comment by ndac-todoroki** [comment]
Sorry for having this plugin not updated. I just made an update which includes this fix. Now you can install 0.1.17 with `asdf install v 0.1.17`.

This was because `v` changed the format of the release tag (before: `vX.Y.Z`, after: `X.Y.Z`). Now this plugin requires to have the "v" if the release tag has it (`asdf install v v0.1.0`).

But actually, I dropped support for versions < `1.1.16` because of the `~/code` directory problem, so no "v"s are required pratically
